### ISSUE TITLE
Docker上にSqlServerをセットアップして、.dacpacの適用を行う。

### ISSUE THREAD

**Issue by CreatioVitae** [CreatioVitae/kashilog#1]
# やりたいこと
Docker上にSqlServerをセットアップして、.dacpacの適用を行う。

## 実際にやること
Docker上にSqlServerをセットアップする。
.dacpacの適用を行う。
上記を半自動で適用できる仕組みを用意する。
上記で用意した永続化層をWebアプリから参照できるようにする。
ローカル開発用とテスト用のSQLServerをDocker上に用意する。

## 完了条件
やることのすべてがmasterにmergeされたら。

**Comment by CreatioVitae** [comment]
# Dockerについての学び
## docker-compose up コマンドで読み込ませるためのyamlファイルのサンプル

version: '3'
services:
mssql:
image: microsoft/mssql-server-linux:latest
container_name: SqlServerTest
ports:
- 14333:15333
environment:
- ACCEPT_EULA=Y
- SA_PASSWORD=P@55w0rd
- MSSQL_TCP_PORT=15333
- MSSQL_PID=Developer
- MSSQL_LCID=1041
- MSSQL_COLLATION=Japanese_CI_AS


### ports: - 1463:1463
⇒ポートフォワーディングの設定

- 左側がホスト（自分がdockerに対してリクエストするとき）のポートの設定
DockerContainerからすると、外に向けて解放している（受け付けている）ポート番号

- 右側がコンテナのポートの設定
DockerContainerから外に向けて通信するときに使うポート番号

この設定をすることで、http://localhost:14333 でDockerContainerに対してリクエストを投げることができ、
そのリクエストを処理した結果をport:15333を通じて返却するような動きになる。

#### ポートの重複について
- ホストのポートの設定が重複する
⇒DockerContainerに関していうと、どのDockerContainerに着信しているかわからない
　⇒×

- コンテナのポートの設定が重複する
予想では同時に使ってたらダメそうだけど・・・
使ってない時ならいける？とはいえそんなの意識するのは面倒だから分けたほうが現実的なのはかわらない。
TBD:実際どうなのか調べる

### SQLServerのContainer別建てが良い？DB(インスタンス)別建てが良い？DB（インスタンス）同じで良い？
#### Docker Imageあれこれ
https://docs.microsoft.com/ja-jp/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver15&pivots=cs1-bash
##### SQLServer2017
- 初のDockerContainerImage
- Ubuntu16.04-basedでうごいている
- 累積更新されていく

##### SQLServer2019
- 複数のOS上でうごく（Redhat,Ubuntu,Windows...)
- MachineLarning対応
- Polybase対応
- MSDTCやReplicationがLinuxのContainerの中でもうごく
- BigDataClustor対応
- GuestOS上でSQLServerを立ち上げてということができるようになっている（2017は、HostOS上（Ubuntu)でしか動かなかったらしい


### yamlファイルで指定する環境変数
https://docs.microsoft.com/ja-jp/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15
#### 今回つかったもの
- ACCEPT_EULA
　使用許諾契約書の承諾を確定する。Y以外ありえない。
- SA_PASSWORD
saアカウントのパスワード
- MSSQL_TCP_PORT
DockerContainerから外にでるためのport指定（省略するとデフォルト値の1433になる)
- MSSQL_LCID
言語ID。1041=日本語
- MSSQL_COLLATION
照合順序。OZmallの場合は、Japanese_CI_AS
- MSSQL_PID
SQLServerのエディションまたはプロダクトキーを設定
#### 今回設定しなかったもの
- MSSQL_MEMORY_LIMIT_MB
　SQL Server が使用できるメモリの最大容量 (MB 単位) を設定する。 何もセットしないと既定値がセットされ、　物理メモリの合計容量の 80% となる。
- MSSQL_IP_ADDRESS
IPアドレスを設定する。IPv4形式である必要がある。
- MSSQL_BACKUP_DIR
既定のバックアップディレクトリを指定する。
- MSSQL_DATA_DIR
mdfファイルが作成されるディレクトリを変更する
TBD:既定がどこかわかってない。
-

### dacpacからの復元

"C:\Program Files\Microsoft SQL Server\150\DAC\bin\sqlpackage" /Action:Publish /tsn:localhost,14333 /tec:False /tdn:Members2 /tu:sa /tp:P@55w0rd /sf:Members2.dacpac

※はまったこと
dacpacファイルをSQLServer2019でとってきていないとダメだった。
SQLServer2016とか2017のDBからとったdacpacファイルだと、SQLServer2019に復元できない
bakファイルとかは出来たのになぁ。。。微妙。

**Comment by endongpz** [comment]
## docker-compose.yamlとは？
既存のDockerImageをつかってDockerContainerをつくるための設定ファイル

## DockerFileとは？
既存のDockerImageをそのまま使うのではなくて、必要なパッケージやアプリ、各種設定を含んだDockerイメージを自分で作成して使用するための設定ファイル（コマンドとかも実行していく）

**Comment by endongpz** [comment]
## DockerFileとは？
既存のDockerImageをそのまま使うのではなくて、必要なパッケージやアプリ、各種設定を含んだDockerイメージを自分で作成して使用するための設定ファイル（コマンドとかも実行していく）
(DockerFileのあるディレクトリに移動して)docker buildコマンドを実行することでdocker imageを作成できる

## DockerFile作成
### DockerFileでまずSQLServerを立ち上げてみる
http://docs.docker.jp/v17.06/engine/reference/builder.html
https://docs.microsoft.com/ja-jp/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15
以下のようなDockerFileでいけた
```
FROM mcr.microsoft.com/mssql/server:2019-latest as Builder

ENV ACCEPT_EULA Y
ENV SA_PASSWORD hoge
ENV MSSQL_PID Developer
ENV MSSQL_LCID 1041
ENV MSSQL_MEMORY_LIMIT_MB 4000
```
- FROM：既存のDockerImage指定
- ENV：環境変数の設定
 - ACCEPT_EULA: 使用許諾契約書の承諾を確定する。Y以外ありえない。
 - SA_PASSWORD: saアカウントのパスワード
 - MSSQL_PID: SQLServerのエディションまたはプロダクトキーを設定。デフォルトはDeveloper
 - MSSQL_LCID: 言語ID。1041=日本語
 - MSSQL_MEMORY_LIMIT_MB: SQL Server が使用できるメモリの最大容量 (MB 単位) を設定する。 何もセットしないと既定値がセットされ、　物理メモリの合計容量の 80% となる。

### dacpacから復元してみる
https://www.wintellect.com/devops-sql-server-dacpac-docker/
```
USER root

RUN apt-get update \
    && apt-get install unzip -y

RUN wget -progress=bar:force -q -O sqlpackage.zip https://go.microsoft.com/fwlink/?linkid=873926 \
    && unzip -qq sqlpackage.zip -d /opt/sqlpackage \
    && chmod +x /opt/sqlpackage/sqlpackage

COPY Database/KashiLogDB.dacpac /tmp/kashilogdb.dacpac

RUN ( /opt/mssql/bin/sqlservr & ) | grep -q "Service Broker manager has started" \
    && /opt/sqlpackage/sqlpackage /a:Publish /tsn:localhost /tdn:KashiLogDB /tu:sa /tp:h0geFuga /sf:/tmp/kashilogdb.dacpac \
    && rm /tmp/kashilogdb.dacpac \
    && pkill sqlservr
```

- unzipとsqlpackageをインストール
※apt-get updateコマンドを実行する権限をつけるために、USER rootを指定

- dacpacをCOPYで持ってきて、sqlpackageの/Action Publishでdacpacの取り込み
※取り込み後は、後始末。rmでCOPYでもってきたdacpacファイルを消し、pkillでsqlserverのプロセスを終了する

## DockerFileからimageをビルドする
以下のようなコマンドでビルドできる（DockerFileのあるディレクトリまで移動しておく必要あり)
```
docker build -t kashilogdb .
```
※-f ファイル名とすることで既定のファイル名（DockerFile)以外のなまえにしても上記コマンドが実行できる
**一番最後の . (ドット)を書かなかったせいで、コマンドがエラーとなりはまった。。。。**

## ビルドしたDockerImageからコンテナーを起動する
以下コマンドでコンテナーが起動できる
```
docker run -p 15331:1433 kashilogdb
```
※-dはバックグラウンド実行するオプション。任意で付ける。
※imageからコンテナを作るときにポートフォワーディング設定を行うので、-p の指定は、この段になる。
**※パスワードはhogeとか本当に簡素なものにすると、セキュリティポリシーにあわないとはじかれるので要注意**

**Comment by CreatioVitae** [comment]
# Docker Containerはシングルプロセスを動かすだけが基本
## キャッシュの考慮も必要
ビルド速度はDeveloperExperienceにかかわる部分なので考慮が必要。

**Comment by endongpz** [comment]
## wgetかcurlか
https://postd.cc/curl-vs-wget/

**Comment by endongpz** [comment]
# docker-compose.yamlでDockerFileを指定して、2つのコンテナーを立ち上げる
```
version: '3.7'

services:
    kashilog-sql-server:
      build:
        context: .
        dockerfile: DockerFile.local
      container_name: KashilogLocalDB
      ports:
        - 15331:1433
    kashilog-test-sql-server:
      build:
        context: .
        dockerfile: DockerFile.test
      container_name: KashilogTestDB
      ports:
        - 15332:1433
```
buildセクションでdockerfileにDockerFileを指定することで、docker-compose upコマンドでdocker containerの立ち上げが出来る。
dockerfileを指定するときに、context : . がないとエラーとなる。

**Comment by endongpz** [comment]
# DockerでkashilogDBを立ち上げる
## SQLServerを立ち上げる
```
FROM mcr.microsoft.com/mssql/server:2017-latest as Builder

ENV ACCEPT_EULA Y
ENV SA_PASSWORD h0geFuga
# SQLServer Edition
ENV MSSQL_PID Developer
# LoCale ID(1041=Japanese)
ENV MSSQL_LCID 1041
ENV MSSQL_MEMORY_LIMIT_MB 4096
```
- FROM mcr.microsoft.com/mssql/server:2017-latest as Builder
   ベースイメージの指定
- ENV ACCEPT_EULA Y
   使用許諾契約書に同意する意思表示
- ENV SA_PASSWORD h0geFuga
   saユーザーのパスワード
- ENV MSSQL_PID Developer
   SQLServerのエディション。省略した場合はデフォルト値（Developer)。あとで見たときに何だっけとなりそうなのとデフォルト値かわったらいやなので明示している。
- ENV MSSQL_LCID
   言語ID。1041=日本語
- ENV MSSQL_MEMORY_LIMIT_MB
   SQLServerのDockerContainerに割り当てられる上限のメモリ使用量。4GBに指定。

### SQLServer2017を使う理由
今回、DBの構造や、データ込みの復元のためにsqlpackageをつかって、dacpacやbacpacを復元する方法を取っている。
復元を行うためには、sqlpackageをインストールする必要があり、
sqlpackageのインストールのために、apt-getを使う必要がある。
Docker上でapt-getを使うときのお作法として、apt-get update → apt-get install → apt-get cleanすることがあげられ、
こちらを行うことで、SQLServer2019だとビルド時に以下エラーに遭遇するようになる。
```
No usable version of the libssl was found
```

これの原因は、
SQLServer2019→デフォルトのimageだと、Ubuntu18の上で動いている
Ubuntu18では、libsslが削除されている。このため、以下のようなエラーに遭遇する。

これを回避するためにUbuntu16の上で動いているSQLServer2017を使うようにした。
(MSDTCとか、ReplicationとかPolyBaseとかMLとか現状使わないんで。)
